### ISSUE TITLE
Export results in .csv formart

### ISSUE THREAD

**Issue by al3mart** [AlexD10S/cli-stackexchange-analyzer#10]
It would be nice if the same information that the script prompts would be exported in a .csv file, for instance.

**Comment by AlexD10S** [comment]
Done with this 2 commits:
https://github.com/AlexD10S/cli-stackexchange-analyzer/commit/f0d3c83bc000cf4e6affa2ddd55dbadde16bb6b9
https://github.com/AlexD10S/cli-stackexchange-analyzer/commit/702c6bf1dedf71572f48dd5515d947b424914f02
